/**
 * .github/scripts/generate-photos.js
 *
 * Auto-runs via GitHub Actions on every push to /photos.
 * Scans folders, reads sidecar .json files, and writes photos.js.
 *
 * ─────────────────────────────────────────────────────────────
 * SMART DEFAULTS (no sidecar needed)
 * ─────────────────────────────────────────────────────────────
 *
 *  Title   — if no title in sidecar, the filename is cleaned up
 *             and used as the title automatically.
 *             e.g. "rainy-night-tokyo.jpg" → "rainy night tokyo"
 *
 *  Camera  — if the filename starts with "16" (e.g. 16_photo.jpg,
 *             16-sunset.jpg, IMG_1600.jpg) the camera is set to
 *             "iPhone 16" automatically unless overridden in sidecar.
 *
 * ─────────────────────────────────────────────────────────────
 * PHOTO SIDECAR  (optional, place next to image file)
 * ─────────────────────────────────────────────────────────────
 *
 *   photos/streets/rainy-night.jpg
 *   photos/streets/rainy-night.json
 *
 *   {
 *     "title":  "rainy night, tokyo",
 *     "date":   "march 2024",
 *     "camera": "fujifilm x100v — f2.0 1/60 iso 3200"
 *   }
 *
 * ─────────────────────────────────────────────────────────────
 * FOLDER METADATA  (optional, controls how folder appears)
 * ─────────────────────────────────────────────────────────────
 *
 *   photos/streets/folder.json
 *
 *   {
 *     "label":       "streets",          ← display name (overrides folder name)
 *     "description": "urban wandering",  ← shown under folder name in grid
 *     "cover":       "rainy-night.jpg",  ← specific cover photo (filename only)
 *     "order":       1                   ← sort order in the directory (lower = first)
 *   }
 *
 * All folder.json fields are optional.
 */

const fs   = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, '..', '..', 'photos');
const OUT_FILE   = path.join(__dirname, '..', '..', 'photos.js');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);

/* ── clean a filename into a readable title ── */
function filenameToTitle(base) {
  return base
    .replace(/[-_]+/g, ' ')       // dashes/underscores → spaces
    .replace(/\.[^.]+$/, '')      // strip leftover extension just in case
    .replace(/\b\w/g, c => c)     // leave lowercase (site style is lowercase)
    .trim();
}

/* ── detect iPhone 16 from filename ── */
function detectCamera(base, metaCamera) {
  if (metaCamera) return metaCamera;
  // matches filenames that START with "16" (digit sequence)
  if (/^16/i.test(base)) return 'iPhone 16';
  return '';
}

function scan() {
  if (!fs.existsSync(PHOTOS_DIR)) {
    fs.mkdirSync(PHOTOS_DIR, { recursive: true });
    return [];
  }

  const entries = fs.readdirSync(PHOTOS_DIR, { withFileTypes: true });
  const dirs    = entries
    .filter(e => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));

  const folders = dirs.map(dir => {
    const folderPath = path.join(PHOTOS_DIR, dir.name);
    const files      = fs.readdirSync(folderPath, { withFileTypes: true });

    /* read optional folder.json */
    let folderMeta = {};
    const folderMetaPath = path.join(folderPath, 'folder.json');
    if (fs.existsSync(folderMetaPath)) {
      try { folderMeta = JSON.parse(fs.readFileSync(folderMetaPath, 'utf8')); } catch(e) {}
    }

    /* collect image files */
    const photos = files
      .filter(f => f.isFile() && IMAGE_EXTS.has(path.extname(f.name).toLowerCase()))
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(f => {
        const base    = path.basename(f.name, path.extname(f.name));
        const sidecar = path.join(folderPath, base + '.json');
        let meta = {};
        if (fs.existsSync(sidecar)) {
          try { meta = JSON.parse(fs.readFileSync(sidecar, 'utf8')); } catch(e) {}
        }

        return {
          src:    `photos/${dir.name}/${f.name}`,
          title:  meta.title  || filenameToTitle(base),
          date:   meta.date   || '',
          camera: detectCamera(base, meta.camera),
        };
      });

    /* resolve cover photo */
    let cover = null;
    if (folderMeta.cover) {
      // specific cover specified in folder.json
      cover = `photos/${dir.name}/${folderMeta.cover}`;
    } else if (photos.length > 0) {
      cover = photos[0].src;
    }

    return {
      name:        folderMeta.label       || dir.name,
      description: folderMeta.description || '',
      order:       folderMeta.order       != null ? folderMeta.order : 999,
      cover,
      photos,
    };
  });

  /* sort by order field, then alphabetically */
  folders.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

  /* strip internal 'order' field from output */
  return folders.map(({ order, ...rest }) => rest);
}

function write(folders) {
  const header = [
    '/* AUTO-GENERATED by .github/scripts/generate-photos.js */',
    '/* Do not edit by hand — push photos to GitHub to update */',
    '',
  ].join('\n');

  const body = 'const FOLDERS = ' + JSON.stringify(folders, null, 2) + ';\n';
  fs.writeFileSync(OUT_FILE, header + body, 'utf8');

  const total = folders.reduce((n, f) => n + f.photos.length, 0);
  console.log(`✓ photos.js written — ${folders.length} folder(s), ${total} photo(s)`);
  folders.forEach(f => {
    console.log(`  ${f.name.padEnd(20)} ${f.photos.length} photo(s)${f.description ? ' — ' + f.description : ''}`);
  });
}

write(scan());
