/**
 * .github/scripts/generate-photos.js
 *
 * Runs automatically via GitHub Actions whenever you push
 * anything inside the /photos folder.
 *
 * What it does:
 *   1. Scans every subfolder inside /photos
 *   2. Finds all image files (.jpg .jpeg .png .webp .gif .avif)
 *   3. For each image, looks for a matching .json sidecar file
 *   4. Writes the full FOLDERS array to photos.js
 *
 * ─────────────────────────────────────────
 * HOW TO ADD METADATA FOR A PHOTO
 * ─────────────────────────────────────────
 * Create a .json file with the same base name as your image:
 *
 *   photos/streets/rainy-night.jpg
 *   photos/streets/rainy-night.json  ← sidecar
 *
 * Sidecar format:
 *   {
 *     "title":  "rainy night, shibuya",
 *     "date":   "march 2024",
 *     "camera": "fujifilm x100v — f2.0 1/60 iso 3200"
 *   }
 *
 * All fields are optional. If you skip the .json the photo
 * still appears — the lightbox will just show "untitled"
 * with no date or camera info.
 */

const fs   = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, '..', '..', 'photos');
const OUT_FILE   = path.join(__dirname, '..', '..', 'photos.js');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);

function scan() {
  if (!fs.existsSync(PHOTOS_DIR)) {
    fs.mkdirSync(PHOTOS_DIR, { recursive: true });
    return [];
  }

  const entries = fs.readdirSync(PHOTOS_DIR, { withFileTypes: true });
  const dirs    = entries
    .filter(e => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));

  return dirs.map(dir => {
    const folderPath = path.join(PHOTOS_DIR, dir.name);
    const files      = fs.readdirSync(folderPath, { withFileTypes: true });

    const photos = files
      .filter(f => f.isFile() && IMAGE_EXTS.has(path.extname(f.name).toLowerCase()))
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(f => {
        const base    = path.basename(f.name, path.extname(f.name));
        const sidecar = path.join(folderPath, base + '.json');
        let meta = {};
        if (fs.existsSync(sidecar)) {
          try { meta = JSON.parse(fs.readFileSync(sidecar, 'utf8')); } catch(e) {}
        }
        return {
          src:    `photos/${dir.name}/${f.name}`,
          title:  meta.title  || '',
          date:   meta.date   || '',
          camera: meta.camera || '',
        };
      });

    return { name: dir.name, photos };
  });
}

function write(folders) {
  const header = [
    '/* AUTO-GENERATED by .github/scripts/generate-photos.js — do not edit by hand */',
    '/* To add metadata, place a .json sidecar next to each image file.             */',
    '/* See .github/scripts/generate-photos.js for the sidecar format.             */',
    '',
  ].join('\n');

  const body = 'const FOLDERS = ' + JSON.stringify(folders, null, 2) + ';\n';

  fs.writeFileSync(OUT_FILE, header + body, 'utf8');

  const totalPhotos = folders.reduce((n, f) => n + f.photos.length, 0);
  console.log(`✓ photos.js written — ${folders.length} folder(s), ${totalPhotos} photo(s)`);
}

write(scan());
