/**
 * .github/scripts/generate-photos.js
 *
 * Scans every subfolder inside /photos and writes photos.js.
 * Runs automatically via GitHub Actions on every push.
 *
 * Photo metadata is read from an optional sidecar JSON file.
 * For a photo called "my-shot.jpg", create "my-shot.json" next to it:
 *
 *   {
 *     "title":  "rainy night, shibuya",
 *     "date":   "march 2024",
 *     "camera": "fujifilm x100v — f2.0 1/60 iso 3200"
 *   }
 *
 * If no sidecar exists the photo still shows — title, date and camera
 * will just be empty in the lightbox.
 */

const fs   = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, '..', '..', 'photos');
const OUT_FILE   = path.join(__dirname, '..', '..', 'photos.js');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif']);

/* ── scan ── */
function scan() {
  if (!fs.existsSync(PHOTOS_DIR)) {
    fs.mkdirSync(PHOTOS_DIR, { recursive: true });
    return [];
  }

  const entries = fs.readdirSync(PHOTOS_DIR, { withFileTypes: true });
  const folders = entries
    .filter(e => e.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name));

  return folders.map(dir => {
    const folderPath = path.join(PHOTOS_DIR, dir.name);
    const files      = fs.readdirSync(folderPath, { withFileTypes: true });

    const photos = files
      .filter(f => f.isFile() && IMAGE_EXTS.has(path.extname(f.name).toLowerCase()))
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(f => {
        const base     = path.basename(f.name, path.extname(f.name));
        const sidecar  = path.join(folderPath, base + '.json');
        let meta       = {};

        if (fs.existsSync(sidecar)) {
          try { meta = JSON.parse(fs.readFileSync(sidecar, 'utf8')); } catch(e) {}
        }

        return {
          src:    `photos/${dir.name}/${f.name}`,
          title:  meta.title  || '',
          date:   meta.date   || '',
          camera: meta.camera || '',
        };
      });

    return { name: dir.name, photos };
  });
}

/* ── write photos.js ── */
function write(folders) {
  const lines = [
    '/* AUTO-GENERATED by .github/scripts/generate-photos.js — do not edit by hand */',
    '/* To add metadata, place a .json sidecar next to each image file.             */',
    '/* See .github/scripts/generate-photos.js for the sidecar format.             */',
    '',
    'const FOLDERS = ' + JSON.stringify(folders, null, 2) + ';',
    '',
  ];

  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`✓ photos.js written — ${folders.length} folder(s), ${folders.reduce((n,f)=>n+f.photos.length,0)} photo(s)`);
}

write(scan());
