/* AUTO-GENERATED by .github/scripts/generate-photos.js */
/* Do not edit by hand — push photos to GitHub to update */
const FOLDERS = [
  {
    "name": "giggles",
    "description": "",
    "cover": "photos/giggles/dogger.png",
    "photos": [
      {
        "src": "photos/giggles/dogger.png",
        "title": "dogger",
        "date": "",
        "camera": ""
      }
    ]
  },
  {
    "name": "pro",
    "description": "",
    "cover": "photos/pro/_DSC8383.JPG",
    "photos": [
      {
        "src": "photos/pro/_DSC8383.JPG",
        "title": "DSC8383",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8432.JPG",
        "title": "DSC8432",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8433.JPG",
        "title": "DSC8433",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8442.JPG",
        "title": "DSC8442",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8445.JPG",
        "title": "DSC8445",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8447.JPG",
        "title": "DSC8447",
        "date": "",
        "camera": ""
      }
    ]
  }
];
