/* AUTO-GENERATED by .github/scripts/generate-photos.js */
/* Do not edit by hand — push photos to GitHub to update */
const FOLDERS = [
  {
    "name": "giggles",
    "description": "",
    "cover": "photos/giggles/dogger.png",
    "photos": [
      {
        "src": "photos/giggles/dogger.png",
        "title": "dogger",
        "date": "",
        "camera": ""
      }
    ]
  },
  {
    "name": "pro",
    "description": "",
    "cover": "photos/pro/_DSC8401.JPG",
    "photos": [
      {
        "src": "photos/pro/_DSC8401.JPG",
        "title": "DSC8401",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8403.JPG",
        "title": "DSC8403",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8406.JPG",
        "title": "DSC8406",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8410.JPG",
        "title": "DSC8410",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8411.JPG",
        "title": "DSC8411",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8412.JPG",
        "title": "DSC8412",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8413.JPG",
        "title": "DSC8413",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8420.JPG",
        "title": "DSC8420",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8422.JPG",
        "title": "DSC8422",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8423.JPG",
        "title": "DSC8423",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8425.JPG",
        "title": "DSC8425",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8430.JPG",
        "title": "DSC8430",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8431.JPG",
        "title": "DSC8431",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8432.JPG",
        "title": "DSC8432",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8433.JPG",
        "title": "DSC8433",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8442.JPG",
        "title": "DSC8442",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8445.JPG",
        "title": "DSC8445",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8447.JPG",
        "title": "DSC8447",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8450 Large.jpeg",
        "title": "DSC8450 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8452 Large.jpeg",
        "title": "DSC8452 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8457 Large.jpeg",
        "title": "DSC8457 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8463 Large.jpeg",
        "title": "DSC8463 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8466 Large.jpeg",
        "title": "DSC8466 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8472 Large.jpeg",
        "title": "DSC8472 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8475 Large.jpeg",
        "title": "DSC8475 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8476 Large.jpeg",
        "title": "DSC8476 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8478 Large.jpeg",
        "title": "DSC8478 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8481 Large.jpeg",
        "title": "DSC8481 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8483 Large.jpeg",
        "title": "DSC8483 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8488 Large.jpeg",
        "title": "DSC8488 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8491 Large.jpeg",
        "title": "DSC8491 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8493 Large.jpeg",
        "title": "DSC8493 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8495 Large.jpeg",
        "title": "DSC8495 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8497 Large.jpeg",
        "title": "DSC8497 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8500 Large.jpeg",
        "title": "DSC8500 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8502 Large.jpeg",
        "title": "DSC8502 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8505 Large.jpeg",
        "title": "DSC8505 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8508 Large.jpeg",
        "title": "DSC8508 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8511 Large.jpeg",
        "title": "DSC8511 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8512 Large.jpeg",
        "title": "DSC8512 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8513 Large.jpeg",
        "title": "DSC8513 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8516 Large.jpeg",
        "title": "DSC8516 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8519 Large.jpeg",
        "title": "DSC8519 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8521 Large.jpeg",
        "title": "DSC8521 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8526 Large.jpeg",
        "title": "DSC8526 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8528 Large.jpeg",
        "title": "DSC8528 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8529 Large.jpeg",
        "title": "DSC8529 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8531 Large.jpeg",
        "title": "DSC8531 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8533 Large.jpeg",
        "title": "DSC8533 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8536 Large.jpeg",
        "title": "DSC8536 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8537 Large.jpeg",
        "title": "DSC8537 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8539 Large.jpeg",
        "title": "DSC8539 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8544 Large.jpeg",
        "title": "DSC8544 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8547 Large.jpeg",
        "title": "DSC8547 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8548 Large.jpeg",
        "title": "DSC8548 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8555 Large.jpeg",
        "title": "DSC8555 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8560 Large.jpeg",
        "title": "DSC8560 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8562 Large.jpeg",
        "title": "DSC8562 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8567 Large.jpeg",
        "title": "DSC8567 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8569 Large.jpeg",
        "title": "DSC8569 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8571 Large.jpeg",
        "title": "DSC8571 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8573 Large.jpeg",
        "title": "DSC8573 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8575 Large.jpeg",
        "title": "DSC8575 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8578 Large.jpeg",
        "title": "DSC8578 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8580 Large.jpeg",
        "title": "DSC8580 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8587 Large.jpeg",
        "title": "DSC8587 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8589 Large.jpeg",
        "title": "DSC8589 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8591 Large.jpeg",
        "title": "DSC8591 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8592 Large.jpeg",
        "title": "DSC8592 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8593 Large.jpeg",
        "title": "DSC8593 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8594 Large.jpeg",
        "title": "DSC8594 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8598 Large.jpeg",
        "title": "DSC8598 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8602 Large.jpeg",
        "title": "DSC8602 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8604 Large.jpeg",
        "title": "DSC8604 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8607 Large.jpeg",
        "title": "DSC8607 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8609 Large.jpeg",
        "title": "DSC8609 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8611 Large.jpeg",
        "title": "DSC8611 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8612 Large.jpeg",
        "title": "DSC8612 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8614 Large.jpeg",
        "title": "DSC8614 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8617 Large.jpeg",
        "title": "DSC8617 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8619 Large.jpeg",
        "title": "DSC8619 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8622 Large.jpeg",
        "title": "DSC8622 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8623 Large.jpeg",
        "title": "DSC8623 Large",
        "date": "",
        "camera": ""
      },
      {
        "src": "photos/pro/_DSC8624 Large.jpeg",
        "title": "DSC8624 Large",
        "date": "",
        "camera": ""
      }
    ]
  }
];
