/* AUTO-GENERATED by .github/scripts/generate-photos.js — do not edit by hand */
/* To add metadata, place a .json sidecar next to each image file.             */
/* See .github/scripts/generate-photos.js for the sidecar format.             */
const FOLDERS = [
  {
    "name": "giggles",
    "photos": [
      {
        "src": "photos/giggles/dogger.png",
        "title": "",
        "date": "",
        "camera": ""
      }
    ]
  }
];
